# Permalinks
permalink:           pretty

# Setup
title:               Meaad AlRshoud
tagline:             Blog
url:                 https://meaad96s.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Meaad AlRshoud
  email:             meaad_r@hotmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Meaad96s

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
  Project 1: '/_posts/2019-09-09-Project-1'
